### ISSUE TITLE
Make links in PDFs clickable

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/paperhive-frontend#108]
Links to an anchor inside the document should be clickable. I'm not so sure about links to another website. Perhaps these links should be opened in a new tab?

@nschloe what do you think?

Thx @carlos-echeverria for reporting!

**Comment by nschloe** [comment]
+1. PDF.js supports that, too, see the demo (https://mozilla.github.io/pdf.js/web/viewer.html).

**Comment by andrenarchy** [comment]
Added in #551
