### ISSUE TITLE
feedback from leuphana

### ISSUE THREAD

**Issue by nschloe** [paperhive/paperhive-frontend#165]
* academia
* [prometheus](http://prometheus-bildarchiv.de/en/databases/index) (art database)
* image annotation  with [hyperimage](http://hyperimage.ws/en/)
* https://www.mysciencework.com/
* plex: scalable media serving
* Sloan foundation
* Show who annotated a paper (similar to "participants" in discussion view)
* labels (aka tag sets) for annotations (standardized labels to avoid that everyone uses their own label):
   * library of congress
   * normdatei
   * limit to a small number of tags (~5?) -> stackexchange
* filtering by users, labels
* hashtags?
* suggest labels from the text (e.g., when mentioning "?", suggest "question")
* www.livemargin.com
  * comment stream has as much room as the text
  * allows for group formation (invitation-based); people feel comfy in committing their ideas into the group. "high signal-to-noise ratio." this is unlike putting out a public comment out.
  * Bob: "Flaw!! Not offline."
* PLOS: "Data retrieved by PLOS." (for metadata) Think about how to represent the data source in general
* http://genius.com/

**Comment by jengeb** [comment]
Tracked in Trello.
