### ISSUE TITLE
suggestions from 42reports discussion (2015-06-26)

### ISSUE THREAD

**Issue by nschloe** [paperhive/paperhive-frontend#183]
* center margin comments at the middle, not the top
* prioritize comment info 
* make clear to user: you can 
   * reply to a comment
   * add a new comment
   * delete a comment
   * editing that removes
   * deletion vs. retraction
* stackoverflow user model
* author identification; make clear if author comments on own paper
* eprint.iacr.org
   * small comments
* allow pure LaTeX input (copy-and-paste from a LaTeX document)
* multiline comments: select a vertical range
* firefox: js errors

**Comment by jengeb** [comment]
Obsolete or moved to Trello.
