### ISSUE TITLE
This document is not open-access and cannot be displayed.

### ISSUE THREAD

**Issue by AlexanderNaydenov** [paperhive/paperhive-frontend#295]
This document is not open-access and cannot be displayed.

NEW: This document is not open-access and cannot be displayed yet.

**Comment by nschloe** [comment]
@AlexanderNaydenov You can easily edit files on GitHub directly and create a PR. If it's just wording, this should be easy to do. Just look for the pencil icon.

**Comment by nschloe** [comment]
Fixed by PR #300.
