### ISSUE TITLE
Logging-in bugs when already logged-in

### ISSUE THREAD

**Issue by AlexanderNaydenov** [paperhive/paperhive-frontend#296]
Trying to log in after already being logged-in leads to an unnecessary  window/message "Signing in failed: Already logging in."
NEW: show the paper I was just  discussing or start page.

![selection_055](https://cloud.githubusercontent.com/assets/5671247/13046069/0bcb0b7c-d3d7-11e5-81da-c8c3945a4b40.png)

![selection_056](https://cloud.githubusercontent.com/assets/5671247/13046081/1e8b452e-d3d7-11e5-92ba-f4332b680ca7.png)

**Comment by nschloe** [comment]
> Trying to log in after already being logged-in

How does this work at all?

**Comment by andrenarchy** [comment]
Probably by going back in the browser history. Maybe this issue is already fixed by a few changes I made to the `authService`?
