### ISSUE TITLE
handle the case where ORCID email isn't published (gravatar, notifications etc.)

### ISSUE THREAD

**Issue by bitgal** [paperhive/paperhive-frontend#299]
add default avatar for a logged in user

**Comment by nschloe** [comment]
We use Gravatar by default I think. What's the matter?

**Comment by bitgal** [comment]
i see no default avatar, just cropped text "osnat avatar" (prob)
not a huge issue but certainly spoils the looks

**Comment by nschloe** [comment]
Screenshot pls.

**Comment by bitgal** [comment]
![image](https://cloud.githubusercontent.com/assets/2675807/13046738/f65f9a1a-d3da-11e5-90ea-752c25c02361.png)

**Comment by bitgal** [comment]
<img width="135" alt="screen shot 2016-02-15 at 11 53 09" src="https://cloud.githubusercontent.com/assets/2675807/13046780/3249f444-d3db-11e5-95d9-04b3bf1a0d5b.png">

**Comment by nschloe** [comment]
That does look messed up. :)

I'll see if I can reproduce this later. Thanks for the report!

**Comment by nschloe** [comment]
Btw how did you login? Google, ORCID, email?

**Comment by bitgal** [comment]
Orcid

**Comment by nschloe** [comment]
Alright! And I suppose you haven't manually set your email address to "public" in ORCID. That'll be the issue: We don't know your email address, and yet we try to show the corresponding gravatar.

**Comment by bitgal** [comment]
ok, so maybe we should show a default avatar in any case we dont have control over?

**Comment by andrenarchy** [comment]
This is actually a backend task, see paperhive/paperhive-backend/issues/64. 

@bitgal do you want to give it a shot?

**Comment by bitgal** [comment]
sure, awesome :)

**Comment by andrenarchy** [comment]
Anyway, it would also be nice if the frontend directive would catch a missing hash and display a default image.

**Comment by andrenarchy** [comment]
The underlying backend issue has been fixed in paperhive/paperhive-backend/pull/70. I'm leaving this open until the gravatar component also falls back to a default image.

**Comment by nschloe** [comment]
PR #77 handles the case for Google logins.

**Comment by nschloe** [comment]
Fixed now.
