### ISSUE TITLE
unauthorized activities should be disabled

### ISSUE THREAD

**Issue by bitgal** [paperhive/paperhive-frontend#301]
NOW: i can for example press 'edit' on someone else's comment, type text etc. only at the end of that process i get the 'unauthorized message on the top (red) bar.

EXPECTED: unauthorized activities are disabled to prevent user's frustration and better UX.

<img width="1071" alt="screen shot 2016-02-15 at 11 59 52" src="https://cloud.githubusercontent.com/assets/2675807/13046872/ad5d01a8-d3db-11e5-9ca9-0d8f6351f8f3.png">

**Comment by bitgal** [comment]
also, the edited text is still shown as if the edit operation was successful - see image above.

**Comment by nschloe** [comment]
Fixed as side effect of PR #303.
