### ISSUE TITLE
unauthorized red bar remains

### ISSUE THREAD

**Issue by bitgal** [paperhive/paperhive-frontend#302]
unauthorized red bar remains after leaving the document screen.
(tried to edit other's comment -> not authorized bar apears ->going to PaperHive home -> red bar still there)

<img width="1272" alt="screen shot 2016-02-15 at 12 02 53" src="https://cloud.githubusercontent.com/assets/2675807/13046971/33321d04-d3dc-11e5-93f7-a84375528a52.png">

**Comment by andrenarchy** [comment]
What do you think about wiping all notifications on a route change?

@jengeb this would also solve the issue with the first login message (click on the link doesn't close the notification).

**Comment by nschloe** [comment]
I'd vote for that.

**Comment by jengeb** [comment]
+1 
I'll take care of that.

**Comment by jengeb** [comment]
Fixed with PR #307.
