### ISSUE TITLE
Use Page Header as a shared part

### ISSUE THREAD

**Issue by pure180** [paperhive/paperhive-frontend#31]
i guess it would be better to use the page header as a shared content element, which will be included with ng-include on the respective site, with dynamic content for each too.

**Comment by nschloe** [comment]
We're talking about this here, right?
```
  <head>
    <meta charset="utf-8">
    <title>PaperHub</title>
    <!-- TODO: bundle mathjax in index.js -->
    <script src="assets/mathjax/MathJax.js?config=TeX-AMS_HTML-full,Safe"></script>

    <link href="index.css" rel="stylesheet">
    <script src="index.js"></script>
  </head>
```
Adapting the page title per view is a good idea, so why not.

**Comment by pure180** [comment]
i meaned this part, it's almost in every page.
[https://github.com/paperhub/paperhub-frontend/blob/page-header/src/templates/user/index.html#L2](page-header)
```
<div class="ph-header ph-header-large ph-xl-margin-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <!-- title -->
          <div class="media">
            <div class="media-left">
              <!--picture-->
              <img class="media-object" ng-src="https://secure.gravatar.com/avatar/{{user.gravatarMd5}}?s=120">
            </div>
            <div class="media-body">
              <!--heading-->
              <h2 class="media-heading">{{user.displayName}}</h2>
              <h4>{{user.userName}}</h4>
              <p class="text-muted">
                <i class="fa fa-fw fa-clock-o"></i> Joined on Jan 3, 1987
              </p>
            </div>
          </div>
        </div>
      </div>
  </div>
```
But i guess adapting the <head></head> per page, with title and meta-tags is needed too.

**Comment by nschloe** [comment]
The link is dead and I only see this code in one place (namely `article/index.html`).

**Comment by pure180** [comment]
The previous html code is from:
[paperhub-frontend/src/templates/user/index.html](https://github.com/paperhub/paperhub-frontend/blob/master/src/templates/user/index.html#L2)
then we a similiar snippet in here:
[paperhub-frontend/src/templates/contact/contact.html] (https://github.com/paperhub/paperhub-frontend/blob/master/src/templates/contact/contact.html)
and on most other pages.

**Comment by andrenarchy** [comment]
The header part will disappear on the document page and the other pages do not use old-school media classes any more.
