### ISSUE TITLE
First user experience tool-tips #betaEdition 

### ISSUE THREAD

**Issue by AlexanderNaydenov** [paperhive/paperhive-frontend#319]
3 tool-tips:
1. Search/Welcome - "Welcome to PaperHive! You can currently search for and discuss all recent mathematics papers on ArXiv. If a an article is missing, you can easily add it from the menu on the left."
2. "Just select some text of interest and ask the research community [your peers?] a question. Save time, help others in real time by replying to their comment, enrich papers with references to other useful research!"
3. "Share the link to this paper with your colleagues and friends and let them answer your question!"

**Comment by jengeb** [comment]
This issue has become obsolete because of the PaperHive tour.
