### ISSUE TITLE
Auto-completion should be turned off in search

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/paperhive-frontend#334]
The native browser auto-completion should be turned off for the search field because it hides part of the search results:

![screenshot from 2016-02-22 19-49-54](https://cloud.githubusercontent.com/assets/1874116/13228683/9187b424-d99d-11e5-82f0-2ec4d1fd7e1c.png)

@jengeb do you know how to do this?

**Comment by jengeb** [comment]
Yes. I'll work on this issue.
