### ISSUE TITLE
Redirect from paid content to free arXiv version

### ISSUE THREAD

**Issue by AlexanderNaydenov** [paperhive/paperhive-frontend#340]
As is: you open a paid paper with our extension but land on a " PDF cannot be displayed: You currently have no access to the PDF." even if there is a free arXiv version.
To be: automatically land on arXiv's version with a small remark that this is the arXiv version.

![image](https://cloud.githubusercontent.com/assets/5671247/13357765/38bf2f04-dcac-11e5-9d98-5b42c6b7c8af.png)

**Comment by jengeb** [comment]
Done.
