### ISSUE TITLE
Usability of comments - Reply

### ISSUE THREAD

**Issue by AlexanderNaydenov** [paperhive/paperhive-frontend#360]
First-time users of PH might not know that they can answer to a comment.
As is: you have to click on a comment to see the "reply" field.
As it could be:
- a mini-button (like Options) that says "Reply"
- have the white "Reply.." field always open

**Comment by andrenarchy** [comment]
Maybe @jengeb has ideas how to improve this UX issue?

**Comment by jengeb** [comment]
This issue has been solved by @andrenarchy.
