### ISSUE TITLE
Deleting a discussion in text view is not working

### ISSUE THREAD

**Issue by jengeb** [paperhive/paperhive-frontend#396]
Console output: 
`TypeError: e.onDiscussionDelete is not a function`

**Comment by andrenarchy** [comment]
Updating a discussion also throws an error. This was probably introduced in the component refactoring. @nschloe any idea?

**Comment by nschloe** [comment]
I'm getting other errors locally atm (`Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:arxiv.org"`), so cannot reproduce atm. Will look at it later today.
