### ISSUE TITLE
PDF cannot be displayed: Cannot read property 'remote' of undefined

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/paperhive-frontend#409]
https://beta.paperhive.org/documents/WIJR7fXHuZuT

![screenshot from 2016-03-28 12-41-47](https://cloud.githubusercontent.com/assets/1874116/14076500/77ca5fae-f4e2-11e5-8249-7a341a3be2ba.png)

**Comment by nschloe** [comment]
This refers to the article [Numerical solution of saddle point problems](http://journals.cambridge.org/abstract_S0962492904000212), apparently without arXiv equivalent. No idea how this ever ended up on PaperHive.

**Comment by andrenarchy** [comment]
The extension probably POSTed the DOI. The problem isn't that the article is imported but that the frontend chokes on articles that don't have an open access version.
